[package]
name = "python"
version = "0.1.0"
authors = ["coco875 <pereira.jannin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustpython = { git = "https://github.com/RustPython/RustPython", version = "0.4.0" }
wasi = "0.11"
